accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from accounts import views

app_name = 'accounts'

urlpatterns = [
    #path('login', views.login, name='login'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token 

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('users/register/', views.UserCreate.as_view()),
    path('login/', obtain_auth_token),
    path('products/', views.ProductList.as_view()),
    path('products/<pk>/', views.ProductDetail.as_view()),
    path('reviews/<pk>/', views.ProductReviews().as_view()), #Get and Post

]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(), name='all'),
   
    path('create/', views.CreateProduct.as_view(), name='create'),
    path('edit/<pk>', views.UpdateProduct.as_view(), name='edit'),
    path('delete/<pk>', views.DeleteProduct.as_view(), name='delete'),
    path('<pk>/', views.ProductDetail.as_view(), name='detail'),
    path('review/<pk>/', views.add_review_to_product, name='add_review_to_product'),
    path('review/<pk>/delete/', views.review_remove, name='delete_review'),
]

recommender_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='produscts')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('auth/', include('social_django.urls', namespace="social")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
  <title>Recommender system</title>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="navbar-brand" href="{% url 'home'%}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'products:all' %}">Products</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'products:create' %}">Create Product</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>


  <div class="container">
    <div class="jumbotron">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    <div>
        <h1>Welcome {{user.username}}!</h1>
    </div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting, you are now signed out!</h1>

{% endblock %}