api/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token 

from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('users/register/', views.UserCreate.as_view()),
    path('login/', obtain_auth_token),
    path('products/', views.ProductList.as_view()),
    path('products/<pk>/', views.ProductDetail.as_view()),
    path('reviews/<pk>/', views.ProductReviews().as_view()), #Get and Post

]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(), name='all'),
   
    path('create/', views.CreateProduct.as_view(), name='create'),
    path('edit/<pk>', views.UpdateProduct.as_view(), name='edit'),
    path('delete/<pk>', views.DeleteProduct.as_view(), name='delete'),
    path('<pk>/', views.ProductDetail.as_view(), name='detail'),
    path('review/<pk>/', views.add_review_to_product, name='add_review_to_product'),
    path('review/<pk>/delete/', views.review_remove, name='delete_review'),
]

recommender_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('products/', include('products.urls', namespace='produscts')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('auth/', include('social_django.urls', namespace="social")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.core.files.storage import FileSystemStorage
User = get_user_model()

class Product(models.Model):
    title = models.TextField(max_length=255)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='media', blank=True)

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    rate = models.CharField(max_length=5)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

products/forms.py
from django import forms
from .models import Product, Review


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('title', 'text', 'image')


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('text', 'rate')

        widgets = {
            'text': forms.Textarea(attrs={'class': 'textinputclass'}),
        }

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Product, Review
from .forms import ProductForm, ReviewForm


class ProductList(ListView):
    model = Product

    def get_queryset(self):
        return Product.objects.all()


class ProductDetail(DetailView):
    model = Product


class CreateProduct(CreateView):
    form_class = ProductForm
    model = Product
    redirect_field_name = 'products/product_detail.html'

    def form_valid(self, form):
        #self.object = form.save(commit=False)
        self.object.image = self.request.FILES
        self.object.save()
        return super().form_valid(form)



class UpdateProduct(UpdateView):
    model = Product
    fields = ['title', 'text', 'image']
    template_name_suffix = '_update'

class DeleteProduct(DeleteView):
    model = Product
    success_url = reverse_lazy('products:all')
    template_name = 'products/product_confirm_delete.html'

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Product Deleted')
        return super().delete(*args, **kwargs)


@login_required
def add_review_to_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.product = product
            review.save()
            return redirect('products:detail', pk=product.pk)
    else:
        form = ReviewForm 
    return render(request, 'products/review_form.html', {'form': form})


@login_required
def review_remove(request, pk):
    review = get_object_or_404(Review, pk=pk)
    product_pk = review.product.pk
    review.delete()
    return redirect('products:detail', pk=product_pk)

products/templates/products/product_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-auto">
    <h3>Are you sure you want to delete this product?</h3>
</div>
<div>
    <p>{{ product }}</p>
</div>
<form method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Confirm Delete">
    <a class="btn btn-simple btn-default" href="{% url 'products:detail' pk=object.pk %}">Cancel</a>
</form>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{ product }}</h2>
    {% if product.image %}
    <div>{{product.image.url}}</div>
    <img src="{{product.image.url}}">
    {% endif %}
    <p>{{ product.text }}</p>

    {% if user.is_authenticated %}
    <a href="{% url 'products:delete' pk=product.pk %}" title="delete" class="btn btn-simple">
        <span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                <path fill-rule="evenodd"
                    d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
            </svg>
        </span>
        <span class="text-danger icon-label">Delete</span>
    </a>
    <a href="{% url 'products:edit' pk=product.pk %}" title="edit" class="btn btn-simple">
        <span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
            </svg>
        </span>
        <span class="text-warning icon-label">Edit</span>
    </a>
    <a href="{% url 'products:add_review_to_product' pk=product.pk %}" title="review" class="btn btn-simple">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-left" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M14 1H2a1 1 0 0 0-1 1v11.586l2-2A2 2 0 0 1 4.414 11H14a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
        </svg>
        <span class="text-primary icon-label">Review</span>
    </a>
    {% endif %}
    <p></p>
    {% if product.reviews.all %}
    {% for review in product.reviews.all %}
    <div>Rate: {{ review.rate }} Author: {{ review.author }}</div>
    <p>Review: {{ review.text }}</p>
    {% endfor %}
    {% else %}
    <h3> No reviews yet </h3>
    {% endif %}

</div>
{% endblock %}

products/templates/products/product_form.html
{% extends "base.html" %}
{% block content %}
<h1>Create a new product</h1>
<form action="{% url 'products:create'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value="Save">
</form>
{% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.title}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}
{% if product_list %}
{% for product in product_list %}
<div>
    <div><a href="{% url 'products:detail' pk=product.pk %}">{{ product }}</a></div>
    {% if product.image %}
    <img src="{{product.image.url}}" style="width:50;height:60px;">
    
    {% endif %}
</div>
{% endfor %}
{% else %}
<h3>No products yet</h3>
{% endif %}
{% endblock %}

products/templates/products/product_update.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Update">
</form>
{% endblock %}

products/templates/products/review_form.html
{% extends "base.html" %}
{% block content %}

  <h1>Review</h1>
  <form class="post-form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Add Review">
  </form>
{% endblock %}